# ------------------------------------------------------------------------
# RF-DETR
# Copyright (c) 2025 Roboflow. All Rights Reserved.
# Licensed under the Apache License, Version 2.0 [see LICENSE for details]
# ------------------------------------------------------------------------

"""Backward-compatibility tests for loading past-version RF-DETR checkpoints.

Each test loads a checkpoint generated by a specific released version of
``rfdetr`` (produced by ``tests/training/generate_checkpoint.py``) using the
*current* codebase.  A test is automatically skipped when the corresponding
checkpoint file is absent — this allows the suite to run locally without any
pre-generated files while still exercising all versions in CI (where the
``ci-checkpoint-compat.yml`` workflow downloads them first).

Checkpoint files are expected at::

    tests/training/checkpoints/checkpoint_v<version>.pth

The list of versions under test is authoritative in
``tests/training/checkpoint_versions.txt``.
"""

from __future__ import annotations

from pathlib import Path

import pytest
import torch

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

_VERSIONS_FILE = Path(__file__).parent / "checkpoint_versions.txt"
_CHECKPOINTS_DIR = Path(__file__).parent / "checkpoints"


def _read_versions() -> list[str]:
    """Parse ``checkpoint_versions.txt`` and return a list of version strings.

    Returns:
        Ordered list of version strings (comment lines and blank lines skipped).
    """
    if not _VERSIONS_FILE.is_file():
        return []
    versions: list[str] = []
    for line in _VERSIONS_FILE.read_text().splitlines():
        stripped = line.strip()
        if stripped and not stripped.startswith("#"):
            versions.append(stripped)
    return versions


def _checkpoint_path(version: str) -> Path:
    """Return the expected checkpoint path for *version*.

    Args:
        version: rfdetr version string, e.g. ``"1.5.0"``.

    Returns:
        Path object (may not yet exist — caller must check).
    """
    return _CHECKPOINTS_DIR / f"checkpoint_v{version}.pth"


def _pytest_params() -> list[pytest.param]:
    """Build parametrize entries — one per version in the versions file.

    A version with no corresponding checkpoint file on disk gets a ``skip``
    mark so the test is visible in the report but does not fail locally.

    Returns:
        List of :class:`pytest.param` objects for ``@pytest.mark.parametrize``.
    """
    params: list[pytest.param] = []
    for version in _read_versions():
        ckpt = _checkpoint_path(version)
        marks = [] if ckpt.is_file() else [pytest.mark.skip(reason=f"checkpoint not found: {ckpt}")]
        params.append(pytest.param(version, marks=marks, id=f"v{version}"))
    if not params:
        # Fallback so parametrize does not produce an empty collection error.
        params.append(
            pytest.param(
                "no-versions",
                marks=[pytest.mark.skip(reason="checkpoint_versions.txt not found or empty")],
                id="no-versions",
            )
        )
    return params


# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------


class TestCheckpointBackwardCompat:
    """Load past-version checkpoints with the current rfdetr codebase.

    Each test parametrized over version exercises the full L1 facade loading
    path (``RFDETRSmall(..., pretrain_weights=path)``), which internally calls
    :func:`rfdetr.models.weights.load_pretrain_weights`.  A successful load
    without exception is the acceptance criterion; we also verify that the
    returned model has the expected number of classes to confirm head alignment.
    """

    @pytest.mark.parametrize("version", _pytest_params())
    def test_load_checkpoint_with_current_code(self, version: str) -> None:
        """Loading a past-version checkpoint must not raise any exception.

        The test uses ``RFDETRSmall`` (the lightest non-nano detection model)
        with ``num_classes`` auto-inferred from the checkpoint, which exercises
        the same loading path used in production fine-tuning workflows.

        Args:
            version: rfdetr version string identifying the checkpoint to load.
        """
        from rfdetr import RFDETRSmall

        ckpt_path = _checkpoint_path(version)
        assert ckpt_path.is_file(), f"Checkpoint missing: {ckpt_path}"

        # Load the checkpoint manually to read the stored class count so we
        # can pass an explicit num_classes and avoid the 90-class COCO default
        # triggering a head mismatch with the 2-class test checkpoint.
        raw: dict = torch.load(ckpt_path, map_location="cpu", weights_only=False)
        stored_num_classes: int | None = None
        if "model" in raw and "class_embed.bias" in raw["model"]:
            stored_num_classes = int(raw["model"]["class_embed.bias"].shape[0]) - 1

        kwargs: dict = dict(pretrain_weights=str(ckpt_path), device="cpu")
        if stored_num_classes is not None:
            kwargs["num_classes"] = stored_num_classes

        # This must not raise — any exception indicates a loading regression.
        loaded = RFDETRSmall(**kwargs)

        # Sanity-check: model is on CPU and has at least one parameter.
        params = list(loaded.model.model.parameters())
        assert params, f"Loaded model for v{version} has no parameters."
        first_device = next(iter(params)).device
        assert str(first_device) == "cpu", f"Expected model on CPU, got {first_device}."

    @pytest.mark.parametrize("version", _pytest_params())
    def test_checkpoint_contains_expected_keys(self, version: str) -> None:
        """Checkpoint file must contain 'model' and 'args' keys.

        Validates that ``generate_checkpoint.py`` produced a structurally
        valid checkpoint file before attempting a full model load.

        Args:
            version: rfdetr version string identifying the checkpoint to load.
        """
        ckpt_path = _checkpoint_path(version)
        assert ckpt_path.is_file(), f"Checkpoint missing: {ckpt_path}"

        ckpt: dict = torch.load(ckpt_path, map_location="cpu", weights_only=False)

        assert "model" in ckpt, f"v{version} checkpoint missing 'model' key; keys present: {list(ckpt.keys())}"
        assert isinstance(ckpt["model"], dict), (
            f"v{version} checkpoint['model'] must be a dict, got {type(ckpt['model']).__name__}"
        )
        assert ckpt["model"], f"v{version} checkpoint['model'] state dict is empty."

        assert "args" in ckpt, f"v{version} checkpoint missing 'args' key; keys present: {list(ckpt.keys())}"

    @pytest.mark.parametrize("version", _pytest_params())
    def test_checkpoint_class_embed_shape_is_valid(self, version: str) -> None:
        """'class_embed.bias' must be present and have shape [N] with N >= 2.

        ``load_pretrain_weights`` reads this tensor to determine the checkpoint
        class count; a missing or malformed tensor causes a ``KeyError`` or
        index error during loading.

        Args:
            version: rfdetr version string identifying the checkpoint to load.
        """
        ckpt_path = _checkpoint_path(version)
        assert ckpt_path.is_file(), f"Checkpoint missing: {ckpt_path}"

        ckpt: dict = torch.load(ckpt_path, map_location="cpu", weights_only=False)
        model_sd: dict[str, torch.Tensor] = ckpt.get("model", {})

        assert "class_embed.bias" in model_sd, (
            f"v{version} checkpoint missing 'class_embed.bias'; "
            f"keys starting with 'class': "
            f"{[k for k in model_sd if k.startswith('class')]}"
        )

        bias = model_sd["class_embed.bias"]
        assert bias.ndim == 1 and bias.shape[0] >= 2, (
            f"v{version} 'class_embed.bias' must be 1-D with ≥ 2 entries, got shape {tuple(bias.shape)}"
        )
